theme: jekyll-theme-slate
title: Pilaster. A dataset of publications and citation metadata on visualization for the digital humanities
description: Pilaster is a collection of citation metadata extracted from publications in visualization for the digital humanities.
